### ISSUE TITLE
New Version of Pyrad

### ISSUE THREAD

**Issue by JugeshHM** [pyradius/pyrad#191] opened 2024-01-25 06:49 UTC
Hi,

Any new version of Pyrad is planned?

Thanks,
Jugesh

**Comment by GIC-de** [comment] 2024-01-25 07:43
Yes it's planned but need to find some time.

**Comment by GIC-de** [comment] 2024-01-25 07:44
Duplicate of #183

**Closed by GIC-de** 2024-01-25 07:44 UTC

**Comment by JugeshHM** [comment] 2024-09-19 06:48
any updates on new version release?
